name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up virtualenv
        run: |
            python3 -m venv ./venv/
            source ./venv/bin/activate
            pip install -r requirements.txt
      
      - name: Check with StrictDoc
        run: |
            source ./venv/bin/activate
            strictdoc export .
